on:
  push: {}
name: Verify Docker setup script
jobs:
  test:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
    - run: echo "${{ secrets.APPLICATION_YML_BASE64 }}" | base64 -d > config/application.yml
    - run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache || true
    - run: docker-compose build
    - run: docker tag devto_web docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache || true
    - run: |
        bin/docker-setup &
        npx wait-on http-get://localhost:3000 -t 1800000
    - run: google-chrome --headless --screenshot=/tmp/screenshot.png --window-size=1280,720 http://localhost:3000
    - uses: actions/upload-artifact@v1
      with:
        name: screenshot
        path: /tmp/screenshot.png
