on:
  push: {}
name: Verify Docker setup script
jobs:
  test:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
    - run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache || true
    - run: docker build . -t devto_web --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache
    - run: docker tag devto_web docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache || true
    - run: |
        bin/docker-setup &
        npx wait-on http-get://localhost:3000 -t 1800000
