on:
  push: {}
name: Verify Docker setup script
jobs:
  test:
    name: Verify Docker setup script
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Inject application config
      run: echo "${{ secrets.APPLICATION_YML_BASE64 }}" | base64 -d > config/application.yml
    - name: Run Docker setup script and wait for web server
      run: |
        bin/docker-setup &
        npx wait-on http-get://localhost:3000 -t 1800000
    - name: Take screenshot
      run: google-chrome --headless --screenshot=/tmp/screenshot.png --window-size=1280,720 http://localhost:3000
    - name: Upload screenshot as artifact
      uses: actions/upload-artifact@v1
      with:
        name: screenshot
        path: /tmp/screenshot.png
